### ISSUE TITLE
Problems with defaultcontentlanguage.

### ISSUE THREAD

**Issue by artelse** [luizdepra/hugo-coder#185]
Hi, am having problems with the `defaultcontentlanguage` setting. When I switch it to `pt-br`, the site by default correctly shows the Portuguese language version. But when I click the English menu item, the page and menu correctly shows in English, but when a menu item is clicked, the _page shows the English version. However the _menus switch back to Portuguese!

**Comment by luizdepra** [comment]
Could you show me your full settings, or better, your full site content so I can test it?
I don't know if a get the problem.

**Comment by artelse** [comment]
It is the default clone from the repo, only changed the `defaultcontentlanguage` setting in `config.toml` to `pt-br`. Then just click English and then a menu item. Then you'll see the menu changed back to Portuguese while page in English. Hope this is clear.

**Comment by luizdepra** [comment]
Ohh, I see!
This is happening because `en` menu items are pointing to a page without the lang code: `/about/` instead of `/en/about/. Page links without lang code point to the default lang version of the page, with is `pt-br` after your change.

There is two ways to fix this problem:
- Change `en` menu links to point to `/en/something/` and `pt-br` to just `/something/`.
- Add `defaultcontentlanguageinsubdir = true` into your configuration and change `en` menu links to `/en/something/`.

**Comment by artelse** [comment]
Ok, got it working now. In addition to your instructions, I also needed to change content file names according to the language; i.e. `about.en.md` and `about.md` for Portuguese.
In conclusion, it was a mismatch. Thx!

**Comment by luizdepra** [comment]
Sure. You're welcome.
