### ISSUE TITLE
How to enable katex by default?

### ISSUE THREAD

**Issue by bebound** [luizdepra/hugo-coder#240]
Add `katex=true` for each file seems redundant. Is this possible to enable it globally?

**Comment by luizdepra** [comment]
I don't think so. But I may be wrong. hahaa
Alternatively you can override [this file](https://github.com/luizdepra/hugo-coder/blob/30850ff725aa5c12d7951c777e10bb9d343e85ba/archetypes/posts.md) and set `katex=true` inside. Every new post will be create with parameter set.

Also, I need to mention that katex and mathjax are only available in `posts`. And, maybe it isn't a good idea to make this configuration global because your pages will load katex even when you don't use it in your text.

**Comment by bebound** [comment]
I see. Because most of my post contains math equations, loading katex for all post is not that expensive for me.

How about changing if condition to `{{- if or (.Params.math) (.Site.Params.math) -}}` in [math.html](https://github.com/luizdepra/hugo-coder/blob/master/layouts/partials/posts/math.html) to make this configurable in `config.toml`?

**Comment by luizdepra** [comment]
I have no objections. Could you open a PR make these changes for `math` and `katex`?
