### ISSUE TITLE
How can I change code format to Highlight.js 

### ISSUE THREAD

**Issue by ZhixiuKang** [luizdepra/hugo-coder#334]
Hi, 
I am trying to change the code formatting to highlight.js and I modified thr header in baseof.html and failed....
Is there any suggestions or ways to modify the code highlights？

Thank you so much！

**Comment by clement-pannetier** [comment]
> I modified thr header in baseof.html and failed....

What did you do exactly ?

> Is there any suggestions or ways to modify the code highlights？

It depends on your hugo version, goldmark (default markdown handler since v0.60) support new features. This theme is using v0.57. Take a look at this documentation:
https://gohugo.io/getting-started/configuration-markup#highlight
https://gohugo.io/content-management/syntax-highlighting/

**Comment by ZhixiuKang** [comment]
Thank you clement-pannetier! I finally made it to highlight.js by adding
```html
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.0.3/styles/atom-one-dark.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.0.3/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
```
to `head` in `hugo-coder/layouts/_default/baseof.html`.
