### ISSUE TITLE
hugo server error

### ISSUE THREAD

**Issue by smazed** [luizdepra/hugo-coder#343]
hi, I'm getting this error every time I try to view the website on my local machine. Can anyone help me fix it? I'm total newbie to this so it would be really great. Thanks in advance!

Error building site: TOCSS: failed to transform "style.coder.css" (text/x-scss): resource "scss/scss/coder.scss_fd4b5b3f9a48bc0c7f005d2f7a4cc30f
" not found in file cache

**Comment by clement-pannetier** [comment]
Hi @smazed, you simply have to download the extended version of Hugo 😉.

**Comment by smazed** [comment]
It's working now! :D

**Comment by luizdepra** [comment]
Nice, so, case closed.

**Comment by KeithETruesdell** [comment]
Something additional to add to this, is that you need the Hugo Extended version.
I personally had MingW and Cygwin installed, so that was causing an issue with me installing from the repo / creating my own binary.

I did download the latest binary and look for the zip file that has "extension" in it.
[https://github.com/gohugoio/hugo/releases](https://github.com/gohugoio/hugo/releases)  
On my Windows machine it was  
[https://github.com/gohugoio/hugo/releases/download/v0.74.3/hugo_extended_0.74.3_Windows-64bit.zip](https://github.com/gohugoio/hugo/releases/download/v0.74.3/hugo_extended_0.74.3_Windows-64bit.zip)
and on my Linux machine it was  
[https://github.com/gohugoio/hugo/releases/download/v0.74.3/hugo_extended_0.74.3_Linux-64bit.deb](https://github.com/gohugoio/hugo/releases/download/v0.74.3/hugo_extended_0.74.3_Linux-64bit.deb)
or   
[https://github.com/gohugoio/hugo/releases/download/v0.74.3/hugo_extended_0.74.3_Linux-64bit.tar.gz](https://github.com/gohugoio/hugo/releases/download/v0.74.3/hugo_extended_0.74.3_Linux-64bit.tar.gz)
(depending on what version you have)
This worked great after that
