### ISSUE TITLE
error while hosting on GitHub

### ISSUE THREAD

**Issue by smazed** [luizdepra/hugo-coder#345]
When I am trying to add a submodule
`git submodule add -b master https://github.com/smazed/smazed.github.io.git public` 
I get the error: 'public' doesn't have a commit checked out
I tried `git add .` it shows fatal: adding files failed

Any help to fix this would be great.
Thanks in advance.

**Comment by latiif** [comment]
What do you mean by `public` in `git submodule add -b master https://github.com/smazed/smazed.github.io.git public`? Is it your themes folder? why `public`?

If you're following a tutorial please link to it, because it can provide us with more context. 

I suggest running `git submodule add https://github.com/luizdepra/hugo-coder.git themes/hugo-coder` from the root folder of your Hugo website.

**Comment by luizdepra** [comment]
I didn't get it too. :laughing:

Well, we can help you if you give us more context. But I need to say that this issue is not related to the theme, so there are better places to find help for git or GHPages deploy problems.

**Comment by smazed** [comment]
Yeah I am following this tutorial- https://youtu.be/5GnFZ8XpMak [41:38] 
I am totally new to this. Sorry if that's a stupid issue but I just can't solve it.

**Comment by luizdepra** [comment]
No problem.
Probably the guy in the video is following [these steps](https://gohugo.io/hosting-and-deployment/hosting-on-github/#github-user-or-organization-pages).
I think you will need to stage the `public` folder and commit it before trying to create the submodule.
