### ISSUE TITLE
dark-mode.js file does not exist in theme (but does in exampleSite) and causes template to fail

### ISSUE THREAD

**Issue by jensenmo** [luizdepra/hugo-coder#389]
The missing file /assets/js/dark-mode.js is causing an issue when the theme is first used: `themes/hugo-coder/layouts/_default/baseof.html:114:29": execute of template failed: template: index.html:114:29: executing "index.html" at <$script.RelPermalink>: nil pointer evaluating resource.Resource.RelPermalink`.
This can be rectified by copying `themes/hugo-coder/exampleSite/assets/js/dark-mode.js` to `themes/hugo-coder/assets/js/dark-mode.js`

**Comment by KeithETruesdell** [comment]
there is a fix in a pull request for this, #387 
that worked
I also just copied the dark-mode.js to the /Theme/assets/js/ folder and this worked
Also, I was not aware, but this needs the "extended" version of Hugo in order to read scss files and such.  Make sure you have that.  I did not, and was not aware of the extended versions.

**Comment by luizdepra** [comment]
I just merged the fix, so closing here. Thank you.
