### ISSUE TITLE
Adding google adsense support?

### ISSUE THREAD

**Issue by matteoredaelli** [luizdepra/hugo-coder#485]
I'd like to add google adsense script. 

Thanks
M

**Comment by luizdepra** [comment]
Hey.

You could fork this theme and add this feature.

**Comment by carvalholeo** [comment]
Hey @matteoredaelli , I'm not an expert on Hugo or in Themes. So, because I'd want to put ads just in articles (and not everywhere), I did a workaround.

First of all, I made customization of the google-analytics template. So, as I already have an AdSense script in a shortcode (it was at every post), I have implemented it as a partial inside the google-analytics template.

Look at this in my repository: https://github.com/carvalholeo/leocarvalho.dev
