### ISSUE TITLE
Add Search capability and TOC

### ISSUE THREAD

**Issue by openact** [luizdepra/hugo-coder#527]
Hi,

  I was wondering, can TOC like [here](https://hugo-theme-even.netlify.app/post/even-preview/) and search like [here](https://adityatelange.github.io/hugo-PaperMod/search/) be implemented in hugo coder theme?
Or is there any way to add it currently? I have close to zero knowledge of JS.

Not an issue exactly but enhancement..

**Comment by luizdepra** [comment]
TOCs is a feature still in TODO. But, It is already possible to add it with some modifications and applying some CSS style. See #415.

Currently, this theme does not provide any way to add a search field.

To be frank, I don't want to add this kind of feature because the philosophy behind the creation of this theme is to provide a minimal looking style without big CSS Frameworks and JS files. The only exceptions are the math symbols (mathjax and katex, both optionals) and analytics tools. Sadly, Hugo doesn't provide a way to pre-render math symbols, and for analytics there is no scape from JS.

But, this is theme is open source, so anyone can fork it and change it as desired. :)

**Comment by Ardemium** [comment]
In my opinion, the only missing feature is the search utility. Sometimes, I want to search for specific keywords within my blog posts rather than relying solely on tags. I strongly agree with the minimalist approach, but I believe the search utility would enhance the theme by providing a multi-purpose function, allowing it to serve as both a blog and a multi-document storage. This would be very useful for coders.
