### ISSUE TITLE
[v2] Template refactor

### ISSUE THREAD

**Issue by luizdepra** [luizdepra/hugo-coder#53]
I think we can improve some templates, maybe splinting them in more files.
It is interesting to read Hugo's template documentation and look for improvements.
Also, I want to review all CSS rules.

Suggested:

- [x] Split files and reuse common code.
- [x] Remove extra whitespaces.
- [x] CSS Rules.
- [ ]  Better image resizing with [Hugo Image Processing](https://gohugo.io/content-management/image-processing/).
- [x]  Configurable date format.
- [x] Move `post` related templates to a separated folder.

**Comment by khos2ow** [comment]
Since the scope of the theme is going beyond the about and post only the immediate suggestions I have for this one move `post`to its own standalone folder. With this move:

- any other list will not be effect posts
- it will be a working example for any other potential list/page (such as `projects`)

I've done this kind of separation in the past, it's quite easy, but I might not have time to do it until next week. So assign this to me also may be?

**Comment by luizdepra** [comment]
These 3 improvements are still wanted.

**Comment by khos2ow** [comment]
I completely forgot about `post` refactor. I'll send a PR soon.
