### ISSUE TITLE
[v2] I18N support

### ISSUE THREAD

**Issue by luizdepra** [luizdepra/hugo-coder#62]
Partially implemented at #40.

I think we should create a the language selector for post and page that have more than one language, but another options are welcome.
We need to read Hugo's i18n docs and look for improvements.

**Comment by khos2ow** [comment]
I volunteer for this one, you can assign it to me.

**Comment by khos2ow** [comment]
We do have the language selector from the top menu, but everything else is hardcoded as English. It requires to convert everything to be read from i18n files (e.g. `<h2>{{ i18n "notFound" }}</h2>` instead of `<h2>Page Not Found</h2>` in `404.html`) and we define supported languages in `/i18n` folder.

But I need to test to see how overriding these language files work. Then even we can expand the functionality to have the site being translated into multiple languages through PRs.

**Comment by jemostrom** [comment]
Stupid question but isn't a language selector in the footer difficult to find, am I missing something?

**Comment by luizdepra** [comment]
@jemostrom, the lang selector shows left from the top menu, separated with a `|`.

**Comment by jemostrom** [comment]
Yes, perhaps I misunderstand what this issue is about ... I thought it was about moving the language selector to the footer

**Comment by khos2ow** [comment]
@jemostrom actually you're correct, I totally missed that part of the original message, but, IMO my suggestions are irrelevant of placement of the language selector menu (which I'm totally fine with it remains on header) and we should implement those in order to have a fully i18n-ready theme.

**Comment by jemostrom** [comment]
I agree on that. It was just the placement I reacted to.

**Comment by luizdepra** [comment]
Sorry, guys. I forgot to remove this part from the description of the issue. We don't need to move the lang selector to the footer.
But, there is something we can look for: a lang indicator for post/pages that have more than one language.

**Comment by luizdepra** [comment]
I think this issue is done with #144.
Now anyone can customize or create a new translation for this theme.
