### ISSUE TITLE
How to add search option in coder theme and put as icon on top right

### ISSUE THREAD

**Issue by tcprks** [luizdepra/hugo-coder#663]
Is there any way to add search option to search the blog posts . Next to these options on main page if a search option comes it will be good.
![image](https://user-images.githubusercontent.com/88808473/156672859-e45d8b1a-384d-487d-88da-faf958b2820b.png)
Sample blog which i have seen, something similar to this can help
Or something similar near to social icon can also help
![image](https://user-images.githubusercontent.com/88808473/156672988-fc932c2b-1dd8-4e7c-855f-08573e4bb8b5.png)

**Comment by luizdepra** [comment]
No, this is not possible without customizing the theme.

I prefer not to add a search feature because I want to avoid bloating the project with unnecessary JS scripts. Google and DuckDuckGo are doing a good job on this area. This theme was meant to be simple and lightweight, avoiding using JS always as possible.

So, you could for the project and attempt to modify it with your needs. Icons are simple to add, you just need to do take the social icons as example and modify the navigation bar. About the search, see [here](https://gohugo.io/tools/search/).
