### ISSUE TITLE
Images not rendering on GitHub pages

### ISSUE THREAD

**Issue by radirobi97** [luizdepra/hugo-coder#679]
Hi all

I have tried to deploy my site by using GitHub pages. However, images are not displaying in my posts.

Images are stored under: **static/images/disk_export.png**, etc..
baseURL = "https://radirobi97.github.io/personal-website/"

I am referencing to my images as `![disk-export](images/disk_export.png)` I have also tried `![disk-export](/images/disk_export.png)`.

None of them worked. What am I doing wrong?

**Comment by radirobi97** [comment]
@luizdepra Would appreciate if you could take a look at this, thank you a lot in advance!

**Comment by radirobi** [comment]
My repository:
https://github.com/radirobi97/personal-website

**Comment by luizdepra** [comment]
This is happening because you have a `folder` in your baseURL, the `personal-website` part.

If you use `/images/disk_export.png` the browser will try to find your file in the root folder of your domain, at `https://radirobi97.github.io/images/disk_export.png`. But your image is being served at `https://radirobi97.github.io/personal-website/images/disk_export.png`. If you use `images/disk_export.png` the browser will try to find your image in a path relative to the current one, at `https://radirobi97.github.io/personal-website/posts/azure-disk/images/disk_export.png`. Also wrong.

So, the easiest way to solve this is to put `/personal-website` in the image address. `![disk-export](/personal-website/images/disk_export.png)`.

**Comment by radirobi97** [comment]
Dear @luizdepra 
thank you for taking the time to answer my question. It has solved the problem. Thank you a lot!
