### ISSUE TITLE
Toggle Buttons not working anymore

### ISSUE THREAD

**Issue by security-prince** [luizdepra/hugo-coder#718]
Hi Everyone,

I am using Hugo with hugo-coder theme, I have this blog [post](https://ishaqmohammed.me/posts/application-security-knowledgebase/) in which I have implemented toggle buttons using markdown and it was working until 22nd August but today when I checked it is not working anymore.
* [Current Link](https://ishaqmohammed.me/posts/application-security-knowledgebase/)
* Wayback URL for the same post on 22nd August: https://web.archive.org/web/20220822080009/https://ishaqmohammed.me/posts/application-security-knowledgebase/
* Markdown Preview Screenshots:

1. https://prnt.sc/4gthOsutM-09
2. https://prnt.sc/jtbosjI-lP80

**Comment by luizdepra** [comment]
I suspect that you have updated Hugo's version and not hugo-coder's, am I right?
(Your versions looks like an old version because the theme toggle is still in the header section.)

Well, I think you will need to activate unsafe rendering by putting these lines in your `config.toml` because you are using raw HTML in your markdown files.
```toml
[markup.goldmark.renderer]
    unsafe = true
```

**Comment by security-prince** [comment]
Aah gotcha, that fixed it. Thank you very much
