### ISSUE TITLE
built-in shortcodes

### ISSUE THREAD

**Issue by khaledngm11** [luizdepra/hugo-coder#727]
I tried to use built-in shortcodes such as **{{< youtube [id] >}}** and that didn't work for me .

**Comment by luizdepra** [comment]
Hey!

Are you using Content-Security-Policy in your configuration?
If so, you need to add `https://www.youtube.com` into `framesrc`.

I'm going to comment the CSP section of the example `config.toml` of this repo. We are having too many issues filled because the CSP is enabled by default in the example.

**Comment by khaledngm11** [comment]
> 
Thanks so much I didn't realize CSP and everything are working now .
