### ISSUE TITLE
Blog config

### ISSUE THREAD

**Issue by nourkagha** [luizdepra/hugo-coder#734]
Hello, this might be a simple question, but I'm wondering:

In config.toml, when I change the Blog menu item URL to be at `/blog` instead of `/posts`, and then rename `content/posts` to `content/blog`, the page title on my website at `domain.tld/blog` becomes 'Blogs' instead of 'Posts'.

Is there a way to keep the page title as 'Posts', while having the URL as `domain.tld/blog` instead of `domain.tld/posts`?

Thank you.

**Comment by curranjohn46** [comment]
I am trying to figure out a similar thing. I added a an additional directory to the menu called "Research."  After accessing Research from the menu I see "Researches" as the title. I tried changing this line in list.html:

    {{- i18n .Data.Plural 1 | title -}}
to 

    {{- i18n .Data.Singular 1 | title -}}

but it continues to render in the plural.

If I figure it out I will share the info. Please do the same. thanks.

**Comment by curranjohn46** [comment]
I added _index.md under my research directory and that fixed the unwanted pluralization.

**Comment by luizdepra** [comment]
@nourkagha and @curranjohn46, this is happening because Hugo has a thing called archetypes. By default, this theme has only two of them: `posts` and `default` (AKA pages). `posts` has comments and other features, `pages` hasn't.

@nourkagha, you could copy every post template to create a new one for `blog`.  But, there is a simpler solution. Keep your files inside `content/posts/`, change their permalink and override the list page, as @curranjohn46 did.

So, in you `config.toml` add this:

```toml
[permalinks]
posts = "/blog/:slug/"
```

And create `content/posts/_index.md` with:

```markdown
+++
title = "Blog"
url = "/blog"
+++
```

Also, don´t forget to change your menu link to `/blog`.

**Comment by nourkagha** [comment]
Perfect, thank you so much for the help and tips!

In my case, I want to keep everything as `posts` (including `content/posts` and the Posts page title), but just access the page through `/blog` instead of `/posts`.

This is possible by following the same steps, but creating `content/posts/_index.md` as follows instead:

    +++
    title = "Posts"
    url = "/blog"
    +++
