### ISSUE TITLE
Dark mode toggle doesn't work on deployed site

### ISSUE THREAD

**Issue by dharmit** [luizdepra/hugo-coder#763]
## Your question

Hi, I suck at HTML, CSS & JS.

I'm using hugo-coder theme for my website and the dark mode toggle works just fine on localhost. But on the real site which I have deployed using Netlify, it doesn't work at all. Can you point what's wrong with my [config?](https://github.com/dharmit/dharmitshah)

The same site worked just fine when deployed on DigitalOcean using Caddy.

**Comment by luizdepra** [comment]
Hey. It seems the problem is not in the hugo's configuration. Yours is very similar to the one we use at https://hugo-coder.netlify.app. If you check the console for errors, you will see something like this error that tells us about the integrity check of the coders.js files.

![image](https://user-images.githubusercontent.com/1427376/213810841-c6b2c7d4-a9f1-47fe-9eaa-f015e3991846.png)

Have enabled any kind of special configuration in Netlify's deployment? Maybe, try checking if you are using the extended version of Hugo.

**Comment by dharmit** [comment]
> try checking if you are using the extended version of Hugo.

Apparently, Netlify uses extended version by default. I found that in the logs:
```
...
8:47:16 AM: Installing Hugo 0.110.0
8:47:17 AM: hugo v0.110.0-e32a493b7826d02763c3b79623952e625402b168+extended linux/amd64 BuildDate=2023-01-17T12:16:09Z VendorInfo=gohugoio
...
...
8:47:23 AM: $ hugo --gc --minify
8:47:23 AM: Start building sites …
8:47:23 AM: hugo v0.110.0-e32a493b7826d02763c3b79623952e625402b168+extended linux/amd64 BuildDate=2023-01-17T12:16:09Z VendorInfo=gohugoio
```
Also, [this comment on Hugo's Discourse](https://discourse.gohugo.io/t/how-do-i-use-hugo-extended-on-netlify/40567/2), kind of confirms that Netlify uses extended version by default.

So far, I haven't found a way to configure Netlify to not use it.

**Comment by dharmit** [comment]
So I ended up moving from Netlify to Firebase. Zero config change. Dark mode toggle works just fine.

My assumption is that it's got something to do with the CloudFront CDN that Netfliy uses.
