### ISSUE TITLE
Setup deploy-preview on Netlify to test PRs

### ISSUE THREAD

**Issue by khos2ow** [luizdepra/hugo-coder#79]
Although this is a _theme_ and not an actual website, but essentially every change we push (thorough pull requests) should be tested against `exampleSite` and we can easily setup a `deploy-preview` pipeline on Netlify to generate the example site for that particular PR at hand to be able to immediately see the change in action without the need to pull down the PR locally to test..

**But** first we need to solve for or come up with a workaround (hopefully not checking-in `resources` folder) for the fact that Netlify cannot handle Hugo extended in their CI.

**Comment by luizdepra** [comment]
There is another problem related with "not checking-in `resources` folder". Hugo's theme showcase apparently doesn't build the resources for us. I'm trying to know why they really don't do this.
If they refuse to build these files, we'll need to add the 'resources' folder into the repository.

This sucks because we'll have to remember and rebuild the resources every time we change the something in the SCSS files. But, in the other hand, the final users won't need to use the extended version anymore (unless they want to override something).

**Comment by luizdepra** [comment]
Yep. There is no way.
https://github.com/gohugoio/hugoThemes/issues/412#issuecomment-421361601

I just added the `resources` folder and a new `release` Makefile command.

I'll update the README with the steps to make a release as soon as possible.

**Comment by khos2ow** [comment]
Whoa. That sucks! I kinda understand position of Netlify to not have extended in their `binrc` base image, but the showcase of Hugo itself won't handle extended is kind of ironic.

But at least on the bright side, we can proceed with deploy-preview.

**Comment by DewaldDeJager** [comment]
I'm trying to deploy my personal site via Netlify but due to the above I am getting the following error:
```
10:47:29 PM: Executing user command: hugo
10:47:29 PM: ERROR 2018/09/21 20:47:29 Failed to add template "posts/single.html" in path "posts/single.html": template: posts/single.html:23: function "resources" not defined
10:47:29 PM: ERROR 2018/09/21 20:47:29 Failed to add template "_default/list.html" in path "_default/list.html": template: _default/list.html:23: function "resources" not defined
10:47:29 PM: ERROR 2018/09/21 20:47:29 Failed to add template "_default/single.html" in path "_default/single.html": template: _default/single.html:23: function "resources" not defined
10:47:29 PM: ERROR 2018/09/21 20:47:29 Failed to add template "index.html" in path "index.html": template: index.html:23: function "resources" not defined
10:47:29 PM: ERROR 2018/09/21 20:47:29 Failed to add template "404.html" in path "404.html": template: 404.html:23: function "resources" not defined
10:47:29 PM: ERROR 2018/09/21 20:47:29 Current theme does not support Hugo version 0.42. Minimum version required is 0.43
10:47:29 PM: Building sites … ERROR 2018/09/21 20:47:29 Error while rendering "page" in "": template: "_default/single.html" is an incomplete or empty template
```

As a workaround, I thought I could build locally and then drag-and-drop the site folder onto Netlify (They also allow this for deploys). Looking into the `release` Makefile command that @luizdepra added, I did not make much progress. The steps I followed were:

```bash
[dearvolt@vostro dearvolt.com]$ cd themes/coder/
[dearvolt@vostro coder]$ ls
archetypes  assets  exampleSite  images  layouts  LICENSE.md  Makefile  README.md  resources  static  theme.toml
[dearvolt@vostro coder]$ make clean release
```

I then open the `demo/public/index.html` page and the site is unstyled. This is the exact same issue I am facing when just running `hugo` in the project root directory. Example screenshot:

![screenshot_2018-09-21 john doe](https://user-images.githubusercontent.com/1856166/45907041-b1f49200-bdf6-11e8-944d-e2cc89e0b1a5.png)

Any ideas on how I can get my site production ready, bearing the above in mind? The site can be found in [this repo](https://github.com/DewaldDeJager/dearvolt.com).

Thank you for the awesome theme and I hope I can contribute!

**Comment by luizdepra** [comment]
I just downloaded your site and ran `hugo serve -D`. Everything looks fine, except the avatar that doesn't appear. I'm using Hugo v0.48/extended.

**Comment by DewaldDeJager** [comment]
@luizdepra I have already tried updating the Hugo version to `0.48` on Netlify. I am running `0.48-1` locally. When I run `hugo server -D` everything works fine for me (Including the avatar), but as soon as I run a static build (`hugo`) then the site looks like the screenshot above.

I get the same behaviour when running `make demo`. The site works fine until I run a release build.

**Comment by luizdepra** [comment]
> I still don't know why running hugo locally and then opening public/index.html shows the unstyled website though.
I think it is because `hugo-coder` uses absolute URL for some links and assets.

**Comment by AndiSusanto15** [comment]
before I apologize for my English. why when I run the hugo blog command that I write doesn't appear in the public folder?

**Comment by AndiSusanto15** [comment]
its awesome themes.

**Comment by AndiSusanto15** [comment]
@DewaldDeJager to generate draft mode must add -D flags, hahahaha. i'm noob.

**Comment by luizdepra** [comment]
Sure. But I don't think this is simple.
I can't simply add this repository to Netlify and run with Hugo configuration because I need the `demo` folder created first. And, I think I can't run `make` on Netlify.

**Comment by luizdepra** [comment]
Ok, I figured it out.
We need a PR to test the deploy hooks. hehehe

**Comment by khos2ow** [comment]
Here's a PR for you: #90 , but the way you setup this integration can be better, I'll send another PR for that.

**Comment by khos2ow** [comment]
and IMO this is the better way of deploying PRs to Netlify: #91
