### ISSUE TITLE
Pagination numbers need more spacing

### ISSUE THREAD

**Issue by JensRantil** [luizdepra/hugo-coder#837]
## Describe the problem:

The pagination numbers are too close to each other. If I have two pages it almost looks like they are the number "12" instead of "1" and "2". I would expect the page numbers to have more spacing between them. Screenshot from https://jensrantil.github.io/posts/ here:

![image](https://github.com/luizdepra/hugo-coder/assets/730342/98af3ea8-7078-42f1-8804-04ed35c53baa)

The source code for the website can be found [here](https://github.com/JensRantil/jensrantil.github.io). I am not using any custom CSS to override the hugo-coder theme.

**Comment by simonhollingshead** [comment]
Luiz, just two comments on this one:

1. It looks like none of the example site pages contain enough content to demonstrate pagination.  Would it be worth either cranking down the number of posts per page in the TOML (e.g. to 8-per-page) or inserting more dummy articles so that pagination can be part of the demo site?
1. The CSS for pagination [looks kind of weird](https://github.com/luizdepra/hugo-coder/blob/main/assets/scss/_pagination.scss).  It specifies that <span> elements inside the li will have a 3.2rem width and be centered, which will force some padding on either side, but the code that actually makes the pagination [never inserts <span> tags around the values](https://github.com/luizdepra/hugo-coder/blob/main/layouts/partials/pagination.html), and even if it did, the spans would default to "display: inline" so the browser would ignore the specified width.  If I forcibly add a <span> around each element and then force the spans to be "display: inline-block" then it looks much wider (possibly too wide), but just looking at that CSS I can't understand what the original intention of it ever was.

**Comment by JensRantil** [comment]
> It seems your browser is picking a font different. Would you mind telling me which one is it? We could add a bit of padding or margin, but I don't think it will look the same for every font.

Sure! MacoSX 13.5.1. Firefox 116.0.3 (64-bit).

**Comment by JensRantil** [comment]
I am also seeing the same font issue in Google Chrome Version 116.0.5845.140 (Official Build) (arm64). Might as well also mention that I have not installed or removed any fonts since I got this laptop.

**Comment by JensRantil** [comment]
Well, this was interesting; I am seeing proper padding when running a local `hugo server serve` (of [this commit](https://github.com/JensRantil/jensrantil.github.io/commit/660763f171d64cb5a7df46d394b993890bb2a634)):

![image](https://github.com/luizdepra/hugo-coder/assets/730342/90a2ea9a-22f9-4bda-a218-3d49a5d449f6)

I have verified that loading https://jensrantil.github.io/posts/ in Firefox 119.0.1 (64-bit, MacOSX) does not yield any 404s of any missing resources (except favicons).

**Comment by JensRantil** [comment]
Okay, I have found the culprit. This does not seem to be a CSS issue per se:

When running `hugo` to build/compile my HTML files it looks like, `hugo` compresses the HTML. When I do `hugo server serve` it doesn't seem to do that. Compressing the HTML means that whitespaces are getting scrubed on https://jensrantil.github.io/posts/ but not when running on my local host. Compare the following two screenshots:

![image](https://github.com/luizdepra/hugo-coder/assets/730342/f31d141d-64e4-4214-a368-6401aab949a0)

![image](https://github.com/luizdepra/hugo-coder/assets/730342/c6a426d3-c3f2-4856-b653-0f2415ddf358)

Compare this (for production):

![image](https://github.com/luizdepra/hugo-coder/assets/730342/056d259d-f528-471f-afed-b1c1147347e0)

...with this (for localhost):

![image](https://github.com/luizdepra/hugo-coder/assets/730342/aac1e381-dbf3-4764-8aa6-75043a356489)

**Comment by JensRantil** [comment]
> Luiz, just two comments on this one:
> 
>     1. It looks like none of the example site pages contain enough content to demonstrate pagination.  Would it be worth either cranking down the number of posts per page in the TOML (e.g. to 8-per-page) or inserting more dummy articles so that pagination can be part of the demo site?

Fixed in https://github.com/luizdepra/hugo-coder/pull/862.

>     2. The CSS for pagination [looks kind of weird](https://github.com/luizdepra/hugo-coder/blob/main/assets/scss/_pagination.scss).  It specifies that span elements inside the li will have a 3.2rem width and be centered, which will force some padding on either side, but the code that actually makes the pagination [never inserts span tags around the values](https://github.com/luizdepra/hugo-coder/blob/main/layouts/partials/pagination.html), and even if it did, the spans would default to "display: inline" so the browser would ignore the specified width.  If I forcibly add a span around each element and then force the spans to be "display: inline-block" then it looks much wider (possibly too wide), but just looking at that CSS I can't understand what the original intention of it ever was.

Fixed in https://github.com/luizdepra/hugo-coder/pull/863 (together with a fix for this issue).

**Comment by luizdepra** [comment]
I think both @JensRantil's PRs fixed it, right?

**Comment by JensRantil** [comment]
> I think both @JensRantil's PRs fixed it, right?

Correct. Fixed in #863.
