### ISSUE TITLE
giscus is not working !

### ISSUE THREAD

**Issue by amriunix** [luizdepra/hugo-coder#839]
## Describe the problem:

I've tried giscus.app by following all the instrauction but seems it's not working !

**Comment by simonhollingshead** [comment]
Just a drive-by guess (because you've not given much information in this issue report), but if you're talking about pages like https://amriunix.com/post/alfresco-reset-password-add-on-0-day-vulnerabilities/ then you're not using the 'posts' content type.  Since you're using /post/ and there's no type called 'post' and there's no type override in your front matter, it's falling back to the standard 'page' type.  Giscus is not inserted into generic non-'post' pages.

**Comment by amriunix** [comment]
Thank you @simonhollingshead, I've fixed using the [Hugo Aliases](https://gohugo.io/content-management/urls/#aliases)
