### ISSUE TITLE
Removing external dependencies

### ISSUE THREAD

**Issue by devinrsmith** [luizdepra/hugo-coder#86]
Hi, thanks for creating the coder theme.

I'm not very well versed in website / front-end best practices. Would it make sense to internalize the external dependencies?

https://github.com/luizdepra/hugo-coder/blob/a6bf2f01503f57444b487a6a058bbe62479f4a5a/layouts/_default/baseof.html#L17-L19

https://github.com/luizdepra/hugo-coder/blob/a6bf2f01503f57444b487a6a058bbe62479f4a5a/layouts/partials/post.html#L8-L9

I know there are pros and cons each way. But from hugo's perspective of serving static files, I think a strong case can be made to have as few external dependencies as possible.

**Comment by luizdepra** [comment]
I disagree. I can't see this relation between static sites and few dependencies. Anyway, I prefer to keep the dependencies the way they are because:

- More files in the repository == More files to update
- Hosting these files in with your site will consume your bandwidth to serve them (sometimes this is a problem)
- CDNs are fast (normallyfaster than normal hosts) 
- Sometimes licenses are tricky

If you compare with other themes, this theme has a small quantity of dependencies. No big and fancy CSS frameworks, no JS (except for MathJax when enabled).

Can we improve something? Yes. Maybe FontAwesome can be replaced by another more lightweight option. Webfonts can be optional and/or configurable.

**Comment by devinrsmith** [comment]
Thanks for your perspective, I think it's very valid.

In *my* perfect world, these external dependencies wouldn't actually be checked in to the repo. They would be pulled in during the hugo (build) phase, checksummed for correctness, and added to the static deployment. The reason why I see a synergy between static sites and no external dependencies is that an external producer might decide to remove (or silently change) their files, aka NPM left-pad fiasco, and now your static deployment is broken. (I do see that some of the external dependencies have an integrity check, which I'm assuming means that at least that can't silently change underneath you.)

Of course, the above takes a bit of leg-work, so it's just my pie-in-the-sky wishes!

I'm very much in favor of CDNs, but would like to serve all assets from my CDN :)

Cheers.

**Comment by luizdepra** [comment]
@xxorde, I think it is feasible but tricky to achieve. But I prefer to make everything internal rather than doing a configuration flag to change dependencies sources.
I would appreciate if someone could work on this.
